import { ISkill, ISkillGroup } from "../interfaces/components";
import { FaJava } from "react-icons/fa";
import { TbSql } from "react-icons/tb";
import {
  SiAppsmith,
  SiBitbucket,
  SiCss,
  SiDocker,
  SiExpo,
  SiExpress,
  SiFastapi,
  SiFigma,
  SiGit,
  SiGithub,
  SiGsap,
  SiHtml5,
  SiJavascript,
  SiJira,
  SiMongodb,
  SiNextdotjs,
  SiNodedotjs,
  SiPostgresql,
  SiPostman,
  SiPrisma,
  SiPython,
  SiReact,
  SiRedux,
  SiShadcnui,
  SiTailwindcss,
  SiThreedotjs,
  SiTypescript,
  SiVercel,
} from "react-icons/si";

export const Skills: ISkill[] = [
  { name: "JavaScript", icon: SiJavascript, color: "#F7DF1E" },
  { name: "TypeScript", icon: SiTypescript, color: "#3178C6" },
  { name: "Python", icon: SiPython, color: "#3776AB" },
  { name: "Java", icon: FaJava, color: "#E76F00" },
  { name: "SQL", icon: TbSql },
  { name: "React", icon: SiReact, color: "#61DAFB" },
  { name: "Next.js", icon: SiNextdotjs },
  { name: "Node.js", icon: SiNodedotjs, color: "#5FA04E" },
  { name: "Express", icon: SiExpress },
  { name: "FastAPI", icon: SiFastapi, color: "#009688" },
  { name: "React Native (Expo)", icon: SiExpo },
  { name: "Redux", icon: SiRedux, color: "#764ABC" },
  { name: "Tailwind CSS", icon: SiTailwindcss, color: "#06B6D4" },
  { name: "shadcn/ui", icon: SiShadcnui },
  { name: "HTML5", icon: SiHtml5, color: "#E34F26" },
  { name: "CSS", icon: SiCss, color: "#663399" },
  { name: "PostgreSQL", icon: SiPostgresql, color: "#4169E1" },
  { name: "MongoDB", icon: SiMongodb, color: "#47A248" },
  { name: "Prisma", icon: SiPrisma },
  { name: "Git", icon: SiGit, color: "#F05032" },
  { name: "GitHub", icon: SiGithub },
  { name: "Bitbucket", icon: SiBitbucket, color: "#0052CC" },
  { name: "Jira", icon: SiJira, color: "#0052CC" },
  { name: "Docker", icon: SiDocker, color: "#2496ED" },
  { name: "Postman", icon: SiPostman, color: "#FF6C37" },
  { name: "Appsmith", icon: SiAppsmith },
  { name: "Vercel", icon: SiVercel },
  { name: "Figma", icon: SiFigma, color: "#F24E1E" },
  { name: "GSAP", icon: SiGsap, color: "#0AE448" },
  { name: "Three.js", icon: SiThreedotjs },
];

export const Coursework: ISkillGroup = {
  category: "Coursework",
  items: [
    "OOPS",
    "DBMS",
    "DSA (500+ solved)",
    "Operating Systems",
    "Computer Networks",
  ],
};
